'use client';

import React from 'react';

import { Footer } from '@/components/layout/Footer';
import { Card } from '@/components/ui/Card';
import { secondaryPageStyles as styles } from '@/app/SecondaryPage.styles';

export default function TermsClient() {
  return (
    <div className={styles.wrapper}>

      <header className={styles.header}>
        <div className="mx-auto max-w-6xl px-6">
          <h1 className={styles.title}>Terms of Service</h1>
          <p className={styles.subtitle}>Legal guidelines for using the Toolioz suite.</p>
        </div>
      </header>

      <section className={styles.contentSection}>
        <div className="mx-auto max-w-6xl px-6">
          <Card className={styles.card}>
            <h2>1. Acceptance of Terms</h2>
            <p>
              By accessing and using Toolioz, you agree to be bound by these terms and all applicable laws and regulations.
              The tools are provided for your convenience, and use indicates acceptance of our privacy-first, zero-server architecture.
            </p>

            <h2>2. No Guarantees or Promises</h2>
            <p>
              All tools, calculators, and information provided on Toolioz are for general informational and educational purposes only. 
              <strong>We do not promise, guarantee, or warrant the accuracy, reliability, completeness, or usefulness of any results.</strong> 
              Financial regulations, tax laws, and market conditions change frequently. You must independently verify all calculations.
            </p>

            <h2>3. No Professional Advice</h2>
            <p>
              Toolioz does not provide financial, legal, tax, or professional advice. The results generated by our tools should never be interpreted as such. 
              You should always consult with a qualified professional before making any financial, legal, or business decisions.
            </p>

            <h2>4. Absolute Disclaimer of Warranties</h2>
            <p>
              The tools and materials on Toolioz are provided strictly on an <strong>"AS IS" and "AS AVAILABLE"</strong> basis. 
              Toolioz explicitly disclaims and negates all warranties, whether expressed or implied, including, but not limited to, 
              implied warranties of merchantability, fitness for a particular purpose, or non-infringement of intellectual property.
            </p>

            <h2>5. Limitation of Liability</h2>
            <p>
              Under no circumstances shall Toolioz, its creators, or its affiliates be liable for any direct, indirect, incidental, 
              special, consequential, or punitive damages. This includes, without limitation, damages for financial loss, loss of data, 
              or loss of profit, arising out of the use, inability to use, or reliance upon the results generated by the tools on this website. 
              You assume total responsibility and risk for your use of the site.
            </p>

            <h2>6. Service Modifications</h2>
            <p>
              Toolioz may revise these terms of service for its website at any time without notice. 
              By using this website you are agreeing to be bound by the then current version of these terms of service.
            </p>

            <p className={styles.lastUpdated}>
              Last Updated: April 2026
            </p>
          </Card>
        </div>
      </section>

      <Footer />
    </div>
  );
}
